name: Deploy Operator
run-name: ${{ format('[{0}][{1}|{2}] Deploy {3} on {4}', github.ref_name, inputs.location, inputs.cluster_pci == true && 'PCI' || 'NPCI', inputs.app_version, inputs.environment) }}
on:
  workflow_dispatch:
    inputs:
      deploy_all:
        type: boolean
        description: 'Deploy All Enviromment'    
      location:
        type: choice
        description: Location
        options: 
        - Brasil
        - Argentina
        - Chile
      environment:
        type: choice
        description: Environment
        options: 
        - dev
        - qa
        - staging
        - prod
      img_version:
        type: string  
        default: ""  
  
jobs:
  check_current_config:
    runs-on: ubuntu-latest
    steps:
      - name: Get data current
        run: |
          echo "Teste"
      - name: Checkout
        uses: actions/checkout@v4